services:
  web:
    image: ruby:3.2
    container_name: roadpass_web
    working_dir: /app
    command: bash -c "bundle install && rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:0@db:5432/roadpass_api_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  sidekiq:
    image: ruby:3.2
    container_name: roadpass_sidekiq
    working_dir: /app
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:0@db:5432/roadpass_api_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: roadpass_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0
      POSTGRES_DB: roadpass_api_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: roadpass_redis
    ports:
      - "6379:6379"

volumes:
  db_data: