default: &default
  adapter: postgresql
  encoding: unicode
  host: db        # <-- Must match the docker-compose service name
  username: postgres
  password: 0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: roadpass_api_development

test:
  adapter: postgresql
  encoding: unicode
  database: roadpass_test
  username: postgres
  password: password
  host: db # matches the service name in docker-compose

production:
  <<: *default
  database: roadpass_api_production
  username: roadpass
  password: <%= ENV['ROADPASS_DATABASE_PASSWORD'] %>